authors:
  Jack Gledhill:
    name: Jack Gledhill
    description: Sudoer
    avatar: /assets/images/people/jack-gledhill.png
    url: https://github.com/Jack-Gledhill
  Ewan Gubb:
    name: Ewan Gubb
    description: Academic Rep
    avatar: /assets/images/people/placeholder.png
  Mesoma Osuji:
    name: Mesoma Osuji
    description: Academic Rep
    avatar: /assets/images/people/placeholder.png
  Jose Gomes:
    name: Jose Gomes
    description: Academic Rep
    avatar: /assets/images/people/placeholders.png
  Yagmur Onal:
    name: Yagmur Onal
    description: Academic Rep
    avatar: /assets/images/people/placeholder.png